# Generated by Django 5.2.5 on 2025-08-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PleasantHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Введите действие привычки', max_length=255, verbose_name='Действие')),
            ],
            options={
                'verbose_name': 'Приятная привычка',
                'verbose_name_plural': 'Приятные привычки',
            },
        ),
        migrations.CreateModel(
            name='UsefulHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Введите место выполнения', max_length=150, verbose_name='Место выполнения')),
                ('time', models.TimeField(help_text='Введите время начала выполнения', verbose_name='Время начала выполнения')),
                ('action', models.CharField(help_text='Введите действие привыки', max_length=255, verbose_name='Действие')),
                ('periodicity', models.IntegerField(default=1, help_text='Укажите периодичность выполнения в днях', verbose_name='Периодичность')),
                ('award', models.CharField(blank=True, help_text='Укажите вознаграждение', max_length=255, null=True, verbose_name='Вознаграждение')),
                ('duration', models.IntegerField(help_text='Укажите продолжительность в секундах', verbose_name='Продолжительность')),
                ('is_published', models.BooleanField(default=True, help_text='Опубликовать привычку?', verbose_name='Признак публичности')),
            ],
            options={
                'verbose_name': 'Полезная привычка',
                'verbose_name_plural': 'Полезные привычки',
            },
        ),
    ]
