# Generated by Django 5.2.5 on 2025-08-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefulhabit',
            name='action',
            field=models.CharField(help_text='Введите действие привычки', max_length=255, verbose_name='Действие'),
        ),
    ]
