# Generated by Django 5.2.5 on 2025-08-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_usefulhabit_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefulhabit',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Опубликовать привычку?', max_length=5, verbose_name='Признак публичности'),
        ),
    ]
